name: Publish

on: [push]

jobs:
    build:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: actions/setup-node@v2.1.5
              with:
                  node-version: 14
                  registry-url: 'https://npm.pkg.github.com'
            - run: npm i
            - name: Publish npm package
              run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
